name: Dependent Jobs Workflow
on:
  push:
    branches: [main]
  pull_request:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for FAIL_ME
        run: |
          if grep -q "FAIL_ME" trigger.txt 2>/dev/null; then
            echo "Found FAIL_ME keyword. Failing job."
            exit 1
          else
            echo "No FAIL_ME keyword. Job passes."
          fi

  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Run second job
        run: echo "Second job runs only if first job passes"
