name: Single Job Hello and Sleep (exp202509042004414)
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  hello_sleep:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "XXX-4 tag-20250904200441"
      - name: Sleep
        run: sleep 600
