name: Test Check
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for fail keyword
        run: |
          if grep -q "FAIL_ME" testfile.txt 2>/dev/null; then
            echo "Found FAIL_ME keyword. Failing job."
            exit 1
          else
            echo "No FAIL_ME keyword. Job passes."
          fi
